#!/bin/bash
# Package images for uploading

set -eux

## Inject Overcloud Images into Undercloud Image
{% for image in overcloud_images %}
md5sum {{ image }} > {{ image }}.md5
{{ virt_customize_base_command }} {{ image }}:/home/stack
{{ virt_customize_base_command }} {{ image }}.md5:/home/stack
{% endfor %}

## Tar overcloud images
{% for image_type in image_types %}
rm -rf {{ image_type }}.d
tar -cf {{ image_type }}.tar {{ image_type }}.*
md5sum {{ image_type }}.tar > {{ image_type }}.tar.md5
{% endfor %}

## Compress intermediate images and undercloud image
## These are not working so replace with copy for now
#virt-sparsify --compress {{ working_dir }}/{{ undercloud_base }} undercloud.qcow2
#rm -f {{ working_dir }}/{{ undercloud_base }}
cp {{ working_dir }}/{{ undercloud_base }} undercloud.qcow2
#virt-sparsify --compress minimal-base.qcow2 minimal-base-compressed.qcow2
#rm -f minimal-base.qcow2
#virt-sparsify --compress overcloud-base.qcow2 overcloud-base-compressed.qcow2
#rm -f overcloud-base.qcow2

## Create md5 for all images
md5sum undercloud.qcow2 > undercloud.qcow2.md5
md5sum minimal-base.qcow2 > minimal-base.qcow2.md5
md5sum overcloud-base.qcow2 > overcloud-base.qcow2.md5