# Summary of the feature set.
# Deploy a containerized Openstack environment using the keystone-only
# scenario (scenario000) and upgrade it

undercloud_setup: true
overcloud_ipv6: false

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

# Container prep parameters.
containerized_overcloud: true
containerized_overcloud_upgrade: true

enable_opstools_repo: true

undercloud_generate_service_certificate: false

ssl_overcloud: false

step_introspect: false

composable_scenario: scenario000-multinode-containers.yaml
upgrade_composable_scenario: scenario000-multinode-containers.yaml
deployed_server: true

test_ping: true
run_tempest: false

# save time by doing a mixed upgrade
step_pre_undercloud_upgrade: true
step_upgrade_undercloud: false
mixed_upgrade: true

# Tripleo-upgrade link
overcloud_upgrade: true

# disable tripleo-upgrade container manipulation.
create_docker_registry: false
use_local_docker_registry: false
create_container_images_download_script: false

container_registry_file: "containers-default-parameters.yaml"

tripleo_ci: true
use_oooq: true

tripleo_upgrade_debug: true
overcloud_ssh_user: "tripleo-admin"

# Mandatory for deployed_servers
tripleo_upgrade_validations_non_fatal: true
# Reduce CI wall time
tripleo_upgrade_converge_plan_only: true

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
