# Featureset for deploying a 2 controller setup using the deployed server
# method
composable_services: false

network_isolation: false
enable_pacemaker: true
overcloud_ipv6: false
containerized_overcloud: true

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
test_ping: false
run_tempest: true
test_regex: 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
composable_roles: false

# Note(trown): The tripleo-ci repo is used here because we do not yet support
# deployed server on libvirt. We will want to move any heat environments we
# use from the tripleo-ci repo to the tripleo-heat-templates repo when we add
# support for deployed server deployments on libvirt.
multinode_args: >-
    -e {{ overcloud_templates_path }}/environments/deployed-server-environment.yaml
    -e {{ overcloud_templates_path }}/ci/environments/multinode-3nodes-registry.yaml
    -r {{ overcloud_templates_path }}/ci/environments/multinode-3nodes.yaml
    -e {{ overcloud_templates_path }}/environments/deployed-server-bootstrap-environment-centos.yaml
    --overcloud-ssh-user {{ undercloud_user }}

deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release not in ['newton','ocata','pike'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  -e {{ working_dir }}/config-download.yaml
  --config-download
  --deployed-server
  --disable-validations
  --verbose
  {%- endif -%}
