---
- name: set_fact for the repo_config path
  set_fact:
    repo_config_path: "{{ working_dir }}/workspace/.quickstart/config/release/dependency_ci/{{ job.dependency|default(dependency) }}/repo_config.yaml"

- name: check if we have a dependency repo_config file
  stat:
    path: "{{ repo_config_path }}"
  register: repo_config_path_check

- name: Include dependency-specific vars
  include_vars: "{{ repo_config_path }}"
  when: repo_config_path_check.stat.exists
