#!/bin/bash
# Validate the overcloud deployment

set -eux

{% if pingtest %}
  {% include 'tripleo-pingtest' %}
{% endif %}

{% if tempest %}
  {% include 'configure-tempest' %}

  {% include 'run-tempest' %}
{% endif %}