# Script and log locations used during the deploy process.
deploy_script: overcloud-deploy.sh.j2
deploy_log: "{{ working_dir }}/overcloud_deploy.log"
post_deploy_script: overcloud-deploy-post.sh.j2
post_deploy_log: "{{ working_dir }}/overcloud_deploy_post.log"
validate_script: overcloud-validate.sh.j2

# `floating_ip_cidr` controls the address range used in the network
# created for tempest tests.  We use Ansible's [ipaddr][] filter to
# calculate addresses within this range so that you can provide a
# different value for `floating_ip_cidr` and in many cases not need to
# change any of the related variables.
#
# [ipaddr]: http://docs.ansible.com/ansible/playbooks_filters_ipaddr.html
floating_ip_cidr: "{{ undercloud_network_cidr|default('192.0.2.0/24') }}"
floating_ip_start: "{{ floating_ip_cidr|nthhost(100) }}"
floating_ip_end: "{{ floating_ip_cidr|nthhost(120) }}"
external_network_gateway: "{{ floating_ip_cidr|nthhost(1) }}"

# Minutes to wait before giving up on the deploy.
deploy_timeout: 90
extra_args: ""
libvirt_args: "--libvirt-type qemu"

# we generally assume that the argument to --control-flavor will
# always be the `oooq_control` that we create from the flavors: key.
# If the deployer needs to use a different name, she can configure a
# `flavor_map` key that will map overcloud roles to specific flavor
# names, like:
#
# flavor_map:
#   control: my_special_control_flavor
#
# This is to avoid having to replace the flavor_args key wholesale for
# a single change.
#
flavor_args: >-
  --control-flavor {{flavor_map.control
  if flavor_map is defined and 'control' in flavor_map else 'oooq_control'}}
  --compute-flavor {{flavor_map.compute
  if flavor_map is defined and 'compute' in flavor_map else 'oooq_compute'}}
  --ceph-storage-flavor {{flavor_map.ceph
  if flavor_map is defined and 'ceph' in flavor_map else 'oooq_ceph'}}

timeout_args: "--timeout {{deploy_timeout}}"

network_args: ""
pacemaker_args: ""

deploy_args: >-
  {{ libvirt_args }}
  {{ flavor_args }}
  {{ timeout_args }}
  {{ network_args }}
  {{ pacemaker_args }}
  {{ extra_args }}

step_deploy_overcloud: true
step_validate_overcloud: true
prepare_tempest: false

# If `test_tempest` is `true`, run tempests tests, otherwise do not
# run them.
test_tempest: false
tempest_regex: ".*smoke"
tempest_workers: 2

# If `test_ping` is `true`, run a simple ping test to validate the
# overcloud.
test_ping: true
