# name and tags
devmode: true
release: master
distro_ver: centos8
overcloud_as_undercloud: true
use_specific_hash: true
docker_registry_host: trunk.registry.rdoproject.org
docker_registry_namespace: tripleomaster
delorean_hash_label: &promotion-testing-tag "{{ dlrn_hash|default(dlrn_hash_tag) }}"
docker_image_tag: *promotion-testing-tag
dlrn_hash_tag_newest: current
promote_source: tripleo-ci-testing
validate_on: rdo

# images
overcloud_image: >-
  {% if whole_disk_images|bool -%}
  overcloud-hardened-uefi-full
  {%- else -%}
  overcloud-full
  {%- endif -%}
overcloud_image_type: >-
  {% if whole_disk_images|bool -%}
  qcow2
  {%- else -%}
  tar
  {%- endif -%}
images:
  - name: "{{ overcloud_image }}"
    url: "{{ overcloud_image_url }}"
    type: "{{ overcloud_image_type }}"
  - name: ipa_images
    url: "{{ ipa_image_url }}"
    type: tar

dlrn_baseurl: https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}
dlrn_hash_tag: tripleo-ci-testing
overcloud_image_url: "https://images.rdoproject.org/{{ distro_ver }}/{{ release }}/rdo_trunk/{{ promote_source }}/{{ overcloud_image }}.{{ overcloud_image_type }}"
ipa_image_url: https://images.rdoproject.org/{{ distro_ver }}/{{ release }}/rdo_trunk/{{ promote_source }}/ironic-python-agent.tar

# NOTE(dviroel): centos-opstools repo is needed for building
#  collectd containers, otherwise keep the current value.
enable_dlrn_deps_opstools: >-
  {% if job is defined and
  job.build_container_images is defined and
  job.build_container_images|default(false)|bool or
  build_container_images|default(false)|bool -%}
  {{ true|bool }}
  {%- else -%}
  {{ enable_opstools_repo|default(false)|bool }}
  {%- endif -%}

# repo setup
# optimize with mirros after we have
# something working..  IMHO may be replaced w/ tripleo-repos setup
# https://review.opendev.org/#/c/709254/
repo_cmd_before: |
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo rm -rf /etc/yum.repos.d/epel*;
  sudo dnf clean all;
  sudo dnf config-manager --disable "*" || true;
  sudo dnf config-manager --enable gating-repo || true;
  if [ -e /etc/ci/mirror_info.sh ]; then
    source /etc/ci/mirror_info.sh
  else
    # Otherwise, fallback to official mirrors provided by CentOS.
    export NODEPOOL_CENTOS_MIRROR={{ ansible_env['NODEPOOL_CENTOS_MIRROR']|default('http://mirror.centos.org/centos', true) }}
    export NODEPOOL_RDO_PROXY=https://trunk.rdoproject.org
  fi
  {% if dlrn_hash_path_newest is defined and dlrn_hash_path_newest %}
    export DLRN_PATH_TAG_NEWEST="current/{{ dlrn_hash_path_newest }}"
  {% elif dlrn_hash_tag_newest is match("^[a-zA-Z0-9]{32}$") %}
    export DLRN_PATH_TAG_NEWEST="current/{{ dlrn_hash_tag_newest[:2] }}/{{ dlrn_hash_tag_newest[2:4] }}/{{ dlrn_hash_tag_newest }}"
  {% else %}
    export DLRN_PATH_TAG_NEWEST="{{ dlrn_hash_tag_newest }}"
  {% endif %}
  {% if dlrn_hash_path is defined and dlrn_hash_path %}
    export DLRN_PATH_TAG="{{ promote_source }}/{{ dlrn_hash_path }}"
  {% elif dlrn_hash_tag is match("^[a-zA-Z0-9]{32}$") %}
    export DLRN_PATH_TAG="{{ promote_source }}/{{ dlrn_hash_tag[:2] }}/{{ dlrn_hash_tag[2:4] }}/{{ dlrn_hash_tag }}"
  {% else %}
    export DLRN_PATH_TAG="{{ dlrn_hash_tag }}"
  {% endif %}
  rdo_dlrn=`curl --silent https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}/${DLRN_PATH_TAG_NEWEST}/delorean.repo -S 2>>~/dlrn_repo_curl_errors.log | grep baseurl | grep "component/tripleo" | cut -d= -f2`
  if [[ -z "$rdo_dlrn" ]]; then
    echo "Failed to parse dlrn hash"
    exit 1
  fi
  export RDO_DLRN_REPO=${rdo_dlrn/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}

  # Save environment variables, to be used afterwards
  echo "export NODEPOOL_CENTOS_MIRROR=${NODEPOOL_CENTOS_MIRROR}" >> {{ repo_setup_env_filepath }}
  echo "export NODEPOOL_RDO_PROXY=${NODEPOOL_RDO_PROXY}" >> {{ repo_setup_env_filepath }}
  echo "export RDO_DLRN_REPO=${RDO_DLRN_REPO}" >> {{ repo_setup_env_filepath }}
  echo "export DLRN_PATH_TAG=${DLRN_PATH_TAG}" >> {{ repo_setup_env_filepath }}

repos:
  - type: file
    filename: delorean.repo
    down_url: "https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}/${DLRN_PATH_TAG}/delorean.repo"

  # ATM current is not used in promotion jobs, this is a bug.
  # However for consistency w/ what is merged. removing
  # See config/release/tripleo-ci/CentOS-7/promotion-testing-hash-master.yml#L48-L64
  # "https://trunk.rdoproject.org/centos8-master/component/tripleo/current/delorean.repo"
  - type: generic
    reponame: delorean-current
    filename: delorean-current.repo
    baseurl: $RDO_DLRN_REPO
    priority: 10
    includepkgs:
      - ansible-role-container-registry
      - ansible-role-tripleo*
      - ansible-tripleo-ipsec
      - instack
      - instack-undercloud
      - openstack-tripleo-*
      - os-apply-config
      - os-collect-config
      - os-net-config
      - os-refresh-config
      - puppet-oslo
      - puppet-cinder
      - puppet-heat
      - puppet-neutron
      - puppet-nova
      - puppet-glance
      - puppet-horizon
      - puppet-ironic
      - puppet-keystone
      - puppet-openstacklib
      - puppet-placement
      - puppet-swift
      - puppet-tripleo
      - python*-tripleo*
      - python*-paunch*
      - paunch-services
      - tripleo-ansible
      - ansible-config_template
      - tripleo-operator-ansible

  - type: file
    filename: delorean-master-deps.repo
    down_url: "https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}/delorean-deps.repo"

  # CentOS related repos
  - type: generic
    reponame: quickstart-centos-base
    filename: quickstart-centos-base.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/BaseOS/x86_64/os/

  - type: generic
    reponame: quickstart-centos-appstreams
    filename: quickstart-centos-appstreams.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/AppStream/x86_64/os/
    exclude:
      - libvirt*
      - python*libvirt*
      - qemu*

  - type: generic
    reponame: quickstart-centos-powertools
    filename: quickstart-centos-powertools.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/PowerTools/x86_64/os/

  - type: generic
    reponame: quickstart-centos-highavailability
    filename: quickstart-centos-highavailability.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/HighAvailability/x86_64/os/

  - type: generic
    reponame: quickstart-centos-extras
    filename: quickstart-centos-extras.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/extras/x86_64/os/

  - type: generic
    reponame: quickstart-centos-ceph-pacific
    filename: quickstart-centos-ceph-pacific.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/storage/x86_64/ceph-pacific
    exclude:
      - ansible*

repo_cmd_after: |

  # # Replace trunk.rdoproject.org to nodepool proxy
  sudo sed -i -e "s|https://trunk.rdoproject.org|$NODEPOOL_RDO_PROXY|g" /etc/yum.repos.d/delorean.repo
  sudo sed -i -e "s|https://trunk.rdoproject.org|$NODEPOOL_RDO_PROXY|g" /etc/yum.repos.d/delorean-master-deps.repo
  sudo sed -i -e "s|http://mirror.centos.org/centos|$NODEPOOL_CENTOS_MIRROR|g" /etc/yum.repos.d/delorean-master-deps.repo
  sudo sed -i -e "s|priority=1|priority=20|g" /etc/yum.repos.d/delorean.repo
  {% if not enable_dlrn_deps_opstools|default(false)|bool %}sudo dnf config-manager --save --setopt centos-opstools.enabled=0;
  {%endif %}
  # continue from here
  sudo rpm -e epel-release || true;
  sudo dnf remove -y rdo-release centos-release-ceph-* centos-release-openstack-* || true;
  sudo rm -rf /etc/yum.repos.d/CentOS-OpenStack-*.repo /etc/yum.repos.d/CentOS-Ceph-*.repo;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  # Save Compose-ID info
  sudo curl -s -o /etc/yum.repos.d/COMPOSE_ID ${NODEPOOL_CENTOS_MIRROR}/8-stream/COMPOSE_ID
  sudo dnf repolist;
  sudo dnf module list;
  sudo dnf module disable container-tools:rhel8 -y;
  sudo dnf module enable container-tools:3.0 -y;
  sudo dnf clean metadata
  {% if repo_setup_run_update|default(true)|bool %}
  sudo dnf update -y
  {% endif %}
undercloud_rpm_dependencies: >-
  python3-tripleoclient
  tripleo-operator-ansible
# Setting base_image_url and base_image_path to overwrite DIB_LOCAL_IMAGE in
# the diskimage-builder
## was https://images.rdoproject.org/base/centos7/CentOS-7-x86_64-GenericCloud-1901.qcow2 - 8 doesn't exit yet
base_image_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20201217.0.x86_64.qcow2
base_image_path: "{{ ansible_user_dir }}/CentOS-Stream-GenericCloud-8-20201217.0.x86_64.qcow2"

# baseos settings
baseos_undercloud_image_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20201217.0.x86_64.qcow2
baseos_image: centos
baseos_image_type: qcow2
baseos_md5sum: "70d5c374156f2ab92c058b6a6150f55e  CentOS-Stream-GenericCloud-8-20201217.0.x86_64.qcow2"
