#!/bin/bash
# Sets up the image building environment

set -eux

yum install -y http://www.rdoproject.org/repos/openstack-liberty/rdo-release-liberty.rpm || true

yum install -y python-tripleoclient
yum install -y libguestfs-tools
yum install -y qemu-kvm libvirt libvirt-python python-lxml

useradd stack
echo "stack ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/stack
chmod 0440 /etc/sudoers.d/stack
usermod -aG libvirtd -G kvm stack

mkdir /home/stack/.ssh
cp /root/.ssh/authorized_keys /home/stack/.ssh
chown -R stack:stack /home/stack/.ssh

## workarounds

### install python-passlib (Should be a req for tripleoclient)
yum install -y python-passlib

### remove EPEL element from image building
sed -i '/epel/d' /usr/share/diskimage-builder/elements/centos7/element-deps

### remove outdated CentOS cloud repo element
sed -i '/centos-cloud-repo/d' /usr/lib/python2.7/site-packages/tripleoclient/v1/overcloud_image.py

### remove dkms install from base element
rm -f /usr/share/diskimage-builder/elements/base/install.d/99-dkms